import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";

const dmMono = DM_Mono({
	weight: ["300", "400", "500"],
	style: ["normal", "italic"],
	subsets: ["latin"],
	variable: "--font-dmmono", // Optional for Tailwind
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${dmMono.variable} ${dmMono.variable} antialiased`}>
				{children}
			</body>
		</html>
	);
}
